name: Otimizador-de-Rotas
description: App desenvolvido para gerar uma lista ordenada de pontos de parada entre dois pontos.
version: 0.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.1.0
